config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :superheroes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/superhero.rb
class Superhero < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/superheroes_controller.rb
require 'pry'

class SuperheroesController < ApplicationController

  def index
    @all = Superhero.all
    
    render 'index'
  end

  def new
  end

  def create
    @superhero = Superhero.create(superhero_params)
    redirect_to @superhero
  end

  def show
    binding.pry
    @superhero = Superhero.find(params[:id])
  end

  def edit
  end

  def delete
  end


  private
    def superhero_params
      params.require(:superhero).permit(:name, :description)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/superheroes_helper.rb
module SuperheroesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandomSuperheroRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/superheroes/index.html.erb
<h1> Welcome to the Rails back-end to the random-superhero application!</h1>

<p>
  all of this will go away when I connect this to the React front-end
</p>

<p>
  Here are all the heroes
</p>

<p>
  <ul>
    <% @all.each do |hero| %>
      <li>
        Name:
        <%= hero.name %><br>
        Description:
        <%= hero.description %><br>
      </li>
    <% end %>
  </ul>
</p>

app/views/superheroes/new.html.erb
<%= form_with  scope: :superhero, url: superheroes_path, local: true do |form| %>

<p>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
</p>

<p>
  <%= form.label :description %><br>
  <%= form.text_area :description %>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>

app/views/superheroes/show.html.erb
<h1><%= "#{@superhero.name} #{@superhero.description}" %> </h1>